services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=shop'
      - 'MARIADB_PASSWORD=test123!@#'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=test'
    ports:
      - '3306:3306'
